### PR TITLE
Update implant.cpp

### PR DESCRIPTION
**Pull request by assume-breach**

### CODE REVIEW

**Comment by bolonobolo** [comment]
I think you pulled this for mistake, anyway a suggestion: leave the credits to previous coders of the droppers :)

**Comment by assume-breach** [comment]
For sure. I wasn't done yet. I was just trying to update but it merged with yours somehow. This thing has completely changed.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by assume-breach** [comment]
Hey man I just wanted to say thanks again for helping me with this. I have the majority of it done, just trying to encrypt a few more strings and i want to get some more pids worked in (maybe onedrive or something). Anway, I'll give you a shoutout on the code when I publish it to Github. Thanks again!

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by bolonobolo** [comment]
Hey dude,
no worries, i'm happy to help peoples on this topics. Can't wait to see 
your dropper!

Have a nice week
Bolo

**Pull request closed without merging**
